name: NW.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - run: zip -r release.zip . -i index.html main.js package.json css config README.md
      name: Zip files
